/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;
import java.util.LinkedList;
import java.io.File;
import java.io.FileNotFoundException;

import org.junit.Test;

import com.google.common.collect.Iterables;

import static org.junit.Assert.*;

public class TestContract {

    File input1 = new File("/Users/lennart/Documents/00_ITU/03_Sem03/02_Applied_Algorithms/Assignment3/route-planning/denmark.graph");

    @Test
    public void testFindDirect(){

    }
}
